const LANGS={
  fr:{flag:'🇫🇷',name:'Français',dir:'ltr',
    appName:'Kyswa Travel',guide:'Meilleur Guide',guideName:'Elhadji Malick Seye',
    accueil:'Accueil',sira:'Sira',infos:'Infos',guide_nav:'Guide',baraka:'Baraka',dhikr:'Dhikr',espace:'Espace',
    notifTitle:'Activer les rappels',notifDesc:'Azan · Sira · Azkar · Salawat',notifBtn:'Activer',
    prochaineP:'Prochaine prière',restant:'restant',tapToSeeHours:'Appuyez pour tous les horaires',
    siraTitle:'Vie du Prophète ﷺ',siraSubtitle:'Leçon quotidienne · Hadith du jour',
    infosTitle:'Infos Pratiques',infosSubtitle:'Climat · Interdits Ihram · Bagages · Santé',
    climat:'🌡️ Climat',interdits:'🚫 Interdits',bagages:'🎒 Bagages',sante:'💊 Santé',
    guideTitle:'Guide Complet Oumra',guideSubtitle:'Invocations étape par étape',
    guideDesc:'Invocations · Tawaf · Sa\'i · Ziara Rawda',
    barakaTitle:'Programme Baraka',hasanat:"VOS HASANAT AUJOURD'HUI",
    barakaDesc:'Azkar · Post-Oumra 40 jours · Hasanat',
    packagesTitle:'Nos Packages 2026',
    boutiqueTitle:'Boutique Kyswa',
    dhikrTitle:'Dhikr & Tasbih',
    espaceTitle:'Mon Espace',espaceSubtitle:'Connectez-vous pour suivre votre parcours',
    email:'Email',mdp:'Mot de passe',connexion:'Se connecter',pasDeCompte:'Pas encore de compte ?',
    demanderAcces:'📋 Demander un accès',deconnexion:'Déconnexion',
    reserverWA:'📱 Réserver via WhatsApp',commanderWA:'📱 Commander via WhatsApp',
    precedente:'← Précédente',suivante:'Suivante →',
    lecon:'LEÇON',hadithJour:'HADITH',
    quotidien:'📿 Quotidien',salawat12k:'🌹 Salawat 12k',postOumra:'🕋 Post-Oumra 40j',
    progrPost:'PROGRESSION POST-OUMRA',accompli:'% accompli',
    mabrouk:'🕋 Guide terminé — Mabrouk !',lecons30:'🌟 30 leçons terminées !',
    envoyerWA:'📱 Envoyer via WhatsApp',retour:'← Retour',
    bilanPrieres:'Bilan de mes prières',toutesPrieres:'✅ Toutes accomplies — +500 Hasanat',
    resetSemaine:'↺ Reset semaine',groupePlus:'+100 en groupe',
    nosPackages:'Nos Packages',zamzamDattes:'Zamzam · Dattes · Parfums',
    quickAccess:'Accès rapide',departIn:'DÉPART DANS',days:'jours',
    duaPerso:'Du\'a Perso',quiz:'Quiz',sadaqa:'Sadaqa',zakat:'Zakat',miras:'Miras',
    promo:'🔥 PROMO',standard:'Standard',vip:'⭐ VIP',premium:'Premium',
    placesLimites:'Places limitées',reserWA:'📱 Réserver via WhatsApp',
    offreLimitee:'🔥 OFFRE LIMITÉE',oumraJuin:'Oumra Juin 2026',datesJuin:'Du 20 au 30 Juin',
    zakatTitle:'⚖️ Calculateur de Zakat',zakatSubtitle:'Calculez votre Zakat selon votre richesse',
    mirasTitle:'📜 Héritage Islamique (Miras)',mirasSubtitle:'Calcul automatique selon le Fiqh',
  },
  en:{flag:'🇬🇧',name:'English',dir:'ltr',
    appName:'Kyswa Travel',guide:'Best Guide',guideName:'Elhadji Malick Seye',
    accueil:'Home',sira:'Sira',infos:'Info',guide_nav:'Guide',baraka:'Baraka',dhikr:'Dhikr',espace:'Space',
    notifTitle:'Enable daily reminders',notifDesc:'Adhan · Sira · Dhikr · Salawat',notifBtn:'Enable',
    prochaineP:'Next prayer',restant:'remaining',tapToSeeHours:'Tap to see all hours',
    siraTitle:'Life of the Prophet ﷺ',siraSubtitle:'Daily lesson · Hadith of the day',
    infosTitle:'Practical Info',infosSubtitle:'Climate · Ihram Rules · Luggage · Health',
    climat:'🌡️ Climate',interdits:'🚫 Prohibitions',bagages:'🎒 Luggage',sante:'💊 Health',
    guideTitle:'Complete Umrah Guide',guideSubtitle:'Step by step invocations',
    guideDesc:'Invocations · Tawaf · Sa\'i · Ziara Rawda',
    barakaTitle:'Baraka Program',hasanat:'YOUR HASANAT TODAY',
    barakaDesc:'Azkar · Post-Umrah 40 days · Hasanat',
    packagesTitle:'Our 2026 Packages',
    boutiqueTitle:'Kyswa Shop',
    dhikrTitle:'Dhikr & Tasbih',
    espaceTitle:'My Space',espaceSubtitle:'Login to track your journey',
    email:'Email',mdp:'Password',connexion:'Login',pasDeCompte:'No account yet?',
    demanderAcces:'📋 Request access',deconnexion:'Logout',
    reserverWA:'📱 Book via WhatsApp',commanderWA:'📱 Order via WhatsApp',
    precedente:'← Previous',suivante:'Next →',
    lecon:'LESSON',hadithJour:'HADITH',
    quotidien:'📿 Daily',salawat12k:'🌹 Salawat 12k',postOumra:'🕋 Post-Umrah 40d',
    progrPost:'POST-UMRAH PROGRESS',accompli:'% complete',
    mabrouk:'🕋 Guide complete — Mabrouk!',lecons30:'🌟 30 lessons done!',
    envoyerWA:'📱 Send via WhatsApp',retour:'← Back',
    bilanPrieres:'My prayer report',toutesPrieres:'✅ All done — +500 Hasanat',
    resetSemaine:'↺ Reset week',groupePlus:'+100 in group',
    nosPackages:'Our Packages',zamzamDattes:'Zamzam · Dates · Perfumes',
    quickAccess:'Quick Access',departIn:'DEPARTURE IN',days:'days',
    duaPerso:'Personal Du\'a',quiz:'Quiz',sadaqa:'Sadaqa',zakat:'Zakat',miras:'Miras',
    promo:'🔥 PROMO',standard:'Standard',vip:'⭐ VIP',premium:'Premium',
    placesLimites:'Limited slots',reserWA:'📱 Book via WhatsApp',
    offreLimitee:'🔥 LIMITED OFFER',oumraJuin:'Umrah June 2026',datesJuin:'June 20 to 30',
    zakatTitle:'⚖️ Zakat Calculator',zakatSubtitle:'Calculate your Zakat based on your wealth',
    mirasTitle:'📜 Islamic Inheritance (Miras)',mirasSubtitle:'Automatic inheritance calculator',
  },
  ar:{flag:'🇸🇦',name:'العربية',dir:'rtl',
    appName:'كيسوا ترافيل',guide:'أفضل مرشد',guideName:'الحاج مالك سي',
    accueil:'الرئيسية',sira:'السيرة',infos:'معلومات',guide_nav:'الدليل',baraka:'البركة',dhikr:'الذكر',espace:'حسابي',
    notifTitle:'تفعيل التنبيهات اليومية',notifDesc:'الأذان · السيرة · الأذكار · الصلاة على النبي',notifBtn:'تفعيل',
    prochaineP:'الصلاة القادمة',restant:'متبقي',tapToSeeHours:'اضغط لمشاهدة جميع الأوقات',
    siraTitle:'حياة النبي ﷺ',siraSubtitle:'درس يومي · حديث اليوم',
    infosTitle:'معلومات عملية',infosSubtitle:'المناخ · محظورات الإحرام · الأمتعة · الصحة',
    climat:'🌡️ المناخ',interdits:'🚫 المحظورات',bagages:'🎒 الأمتعة',sante:'💊 الصحة',
    guideTitle:'دليل العمرة الكامل',guideSubtitle:'الأدعية خطوة بخطوة',
    guideDesc:'الأدعية · الطواف · السعي · الروضة الشريفة',
    barakaTitle:'برنامج البركة',hasanat:'حسناتك اليوم',
    barakaDesc:'أذكار · ما بعد العمرة 40 يوم · حسنات',
    packagesTitle:'باقاتنا 2026',
    boutiqueTitle:'متجر كيسوا',
    dhikrTitle:'الذكر والتسبيح',
    espaceTitle:'حسابي',espaceSubtitle:'سجّل دخولك لمتابعة رحلتك',
    email:'البريد الإلكتروني',mdp:'كلمة المرور',connexion:'تسجيل الدخول',pasDeCompte:'ليس لديك حساب؟',
    demanderAcces:'📋 طلب وصول',deconnexion:'تسجيل الخروج',
    reserverWA:'📱 احجز عبر واتساب',commanderWA:'📱 اطلب عبر واتساب',
    precedente:'→ السابق',suivante:'التالي ←',
    lecon:'الدرس',hadithJour:'الحديث',
    quotidien:'📿 يومي',salawat12k:'🌹 الصلاة 12k',postOumra:'🕋 ما بعد العمرة 40 يوم',
    progrPost:'تقدم ما بعد العمرة',accompli:'٪ مكتمل',
    mabrouk:'🕋 اكتمل الدليل — مبروك!',lecons30:'🌟 اكتملت 30 درساً!',
    envoyerWA:'📱 أرسل عبر واتساب',retour:'رجوع →',
    bilanPrieres:'تقرير صلواتي',toutesPrieres:'✅ كل الصلوات — +500 حسنة',
    resetSemaine:'↺ إعادة الأسبوع',groupePlus:'+100 جماعة',
    nosPackages:'باقاتنا',zamzamDattes:'زمزم · تمر · عطور',
    quickAccess:'وصول سريع',departIn:'المغادرة خلال',days:'يوم',
    duaPerso:'دعاء شخصي',quiz:'مسابقة',sadaqa:'صدقة',zakat:'زكاة',miras:'ميراث',
    promo:'🔥 عرض',standard:'قياسي',vip:'⭐ VIP',premium:'ممتاز',
    placesLimites:'أماكن محدودة',reserWA:'📱 احجز عبر واتساب',
    offreLimitee:'🔥 عرض محدود',oumraJuin:'عمرة يونيو 2026',datesJuin:'من 20 إلى 30 يونيو',
    zakatTitle:'⚖️ حاسبة الزكاة',zakatSubtitle:'احسب زكاتك حسب ثروتك',
    mirasTitle:'📜 الميراث الإسلامي',mirasSubtitle:'حاسبة الميراث التلقائية',
  },
  wo:{flag:'🌍',name:'Wolof',dir:'ltr',
    appName:'Kyswa Travel',guide:'Guide bu baax',guideName:'Elhadji Malick Seye',
    accueil:'Kër',sira:'Sira',infos:'Xibaar',guide_nav:'Guide',baraka:'Baraka',dhikr:'Dhikr',espace:'Sama Nokk',
    notifTitle:'Seeteel yëgëleem yi',notifDesc:'Azan · Sira · Dhikr · Salawat',notifBtn:'Seet',
    prochaineP:'Jikko bi dëkk',restant:'def',tapToSeeHours:'Cuqal ngir xool waxtu yi',
    siraTitle:'Yëgëleem Nabi ﷺ',siraSubtitle:'Ders bu bépp bés · Hadith',
    infosTitle:'Xibaar yu malal',infosSubtitle:'Xëlam · Ihram · Valiz · Wérëf',
    climat:'🌡️ Xëlam',interdits:'🚫 Yëgël doo def',bagages:'🎒 Valiz',sante:'💊 Wérëf',
    guideTitle:'Guide Oumra bu xëtu',guideSubtitle:'Duwaaw ci kéb kéb',
    guideDesc:'Duwaaw · Tawaf · Sa\'i · Rawda',
    barakaTitle:'Programme Baraka',hasanat:'SA HASANAT TËEY',
    barakaDesc:'Azkar · Gannaaw Oumra 40 bés · Hasanat',
    packagesTitle:'Ak Packages yi 2026',
    boutiqueTitle:'Boutique Kyswa',
    dhikrTitle:'Dhikr & Tasbih',
    espaceTitle:'Sama Nokk',espaceSubtitle:'Dugël ngir xool sa yëgëleem',
    email:'Email',mdp:'Mot de passe',connexion:'Dugël',pasDeCompte:'Amul konte?',
    demanderAcces:'📋 Dëmmeel accès',deconnexion:'Fey',
    reserverWA:'📱 Jël ci WhatsApp',commanderWA:'📱 Yëgël ci WhatsApp',
    precedente:'← Yangi',suivante:'Ci kanam →',
    lecon:'DERS',hadithJour:'HADITH',
    quotidien:'📿 Bépp bés',salawat12k:'🌹 Salawat 12k',postOumra:'🕋 Gannaaw Oumra 40j',
    progrPost:'PROGRESS GANNAAW OUMRA',accompli:'% jeex',
    mabrouk:'🕋 Guide jeex — Mabrouk!',lecons30:'🌟 Ders 30 jeex!',
    envoyerWA:'📱 Yónnee ci WhatsApp',retour:'← Dellu',
    bilanPrieres:'Sama jikko yi',toutesPrieres:'✅ Jikko yépp — +500 Hasanat',
    resetSemaine:'↺ Reboot ayu-bés',groupePlus:'+100 ci simili',
    nosPackages:'Packages yi',zamzamDattes:'Zamzam · Tamer · Pafin',
    quickAccess:'Ubbil gaaw',departIn:'YÉGG CI',days:'bés',
    duaPerso:'Du\'a Bopp',quiz:'Quiz',sadaqa:'Sadaqa',zakat:'Zakat',miras:'Miras',
    promo:'🔥 PROMO',standard:'Standard',vip:'⭐ VIP',premium:'Premium',
    placesLimites:'Wanak yi limited',reserWA:'📱 Jël ci WhatsApp',
    offreLimitee:'🔥 JEEXAL NA',oumraJuin:'Oumra Juin 2026',datesJuin:'20 ba 30 Juin',
    zakatTitle:'⚖️ Nattukaayu Saka',zakatSubtitle:'Nattal sa saka ci sa alal',
    mirasTitle:'📜 Nattukaayu Dono (Miras)',mirasSubtitle:'Nattukaay bi kiy doxal dono islam',
  },
  es:{flag:'🇪🇸',name:'Español',dir:'ltr',
    appName:'Kyswa Travel',guide:'Mejor Guía',guideName:'Elhadji Malick Seye',
    accueil:'Inicio',sira:'Sira',infos:'Info',guide_nav:'Guía',baraka:'Baraka',dhikr:'Dhikr',espace:'Mi Espacio',
    notifTitle:'Activar recordatorios',notifDesc:'Adhan · Sira · Dhikr · Salawat',notifBtn:'Activar',
    prochaineP:'Próxima oración',restant:'restante',tapToSeeHours:'Toca para ver horarios',
    siraTitle:'Vida del Profeta ﷺ',siraSubtitle:'Lección diaria · Hadith del día',
    infosTitle:'Información Práctica',infosSubtitle:'Clima · Prohibiciones Ihram · Equipaje · Salud',
    climat:'🌡️ Clima',interdits:'🚫 Prohibiciones',bagages:'🎒 Equipaje',sante:'💊 Salud',
    guideTitle:'Guía Completa de Umrah',guideSubtitle:'Invocaciones paso a paso',
    guideDesc:'Invocaciones · Tawaf · Sa\'i · Ziara Rawda',
    barakaTitle:'Programa Baraka',hasanat:'TUS HASANAT HOY',
    barakaDesc:'Azkar · Post-Umrah 40 días · Hasanat',
    packagesTitle:'Nuestros Paquetes 2026',
    boutiqueTitle:'Tienda Kyswa',
    dhikrTitle:'Dhikr & Tasbih',
    espaceTitle:'Mi Espacio',espaceSubtitle:'Inicia sesión para seguir tu voyage',
    email:'Correo electrónico',mdp:'Contraseña',connexion:'Iniciar sesión',pasDeCompte:'¿Sin cuenta aún?',
    demanderAcces:'📋 Solicitar acceso',deconnexion:'Cerrar sesión',
    reserverWA:'📱 Reservar por WhatsApp',commanderWA:'📱 Pedir por WhatsApp',
    precedente:'← Anterior',suivante:'Siguiente →',
    lecon:'LECCIÓN',hadithJour:'HADITH',
    quotidien:'📿 Diario',salawat12k:'🌹 Salawat 12k',postOumra:'🕋 Post-Umrah 40d',
    progrPost:'PROGRESO POST-UMRAH',accompli:'% completado',
    mabrouk:'🕋 Guía completa — ¡Mabrouk!',lecons30:'🌟 ¡30 lecciones completadas!',
    envoyerWA:'📱 Enviar por WhatsApp',retour:'← Volver',
    bilanPrieres:'Mis oraciones de hoy',toutesPrieres:'✅ Todas completas — +500 Hasanat',
    resetSemaine:'↺ Reiniciar semana',groupePlus:'+100 en grupo',
    nosPackages:'Nuestros Paquetes',zamzamDattes:'Zamzam · Dátiles · Perfumes',
    quickAccess:'Acceso rápido',departIn:'SALIDA EN',days:'días',
    duaPerso:'Du\'a Personal',quiz:'Quiz',sadaqa:'Sadaqa',zakat:'Zakat',miras:'Miras',
    promo:'🔥 PROMO',standard:'Estándar',vip:'⭐ VIP',premium:'Premium',
    placesLimites:'Plazas limitadas',reserWA:'📱 Reservar por WhatsApp',
    offreLimitee:'🔥 OFERTA LIMITADA',oumraJuin:'Umrah Junio 2026',datesJuin:'Del 20 al 30 de Junio',
    zakatTitle:'⚖️ Calculadora de Zakat',zakatSubtitle:'Calcula tu Zakat según tu riqueza',
    mirasTitle:'📜 Herencia Islámica (Miras)',mirasSubtitle:'Calculadora automática de sucesiones',
  },
  it:{flag:'🇮🇹',name:'Italiano',dir:'ltr',
    appName:'Kyswa Travel',guide:'Miglior Guida',guideName:'Elhadji Malick Seye',
    accueil:'Home',sira:'Sira',infos:'Info',guide_nav:'Guida',baraka:'Baraka',dhikr:'Dhikr',espace:'Il Mio Spazio',
    notifTitle:'Attiva i promemoria',notifDesc:'Adhan · Sira · Dhikr · Salawat',notifBtn:'Attiva',
    prochaineP:'Prossima preghiera',restant:'rimanente',tapToSeeHours:'Tocca per tutti gli orari',
    siraTitle:'Vita del Profeta ﷺ',siraSubtitle:'Lezione quotidiana · Hadith del giorno',
    infosTitle:'Informazioni Pratiche',infosSubtitle:'Clima · Divieti Ihram · Bagagli · Salute',
    climat:'🌡️ Clima',interdits:'🚫 Divieti',bagages:'🎒 Bagagli',sante:'💊 Salute',
    guideTitle:'Guida Completa Umrah',guideSubtitle:'Invocations passe après passe',
    guideDesc:'Invocazioni · Tawaf · Sa\'i · Ziara Rawda',
    barakaTitle:'Programma Baraka',hasanat:'I TUOI HASANAT OGGI',
    barakaDesc:'Azkar · Post-Umrah 40 giorni · Hasanat',
    packagesTitle:'I Nostri Pacchetti 2026',
    boutiqueTitle:'Negozio Kyswa',
    dhikrTitle:'Dhikr & Tasbih',
    espaceTitle:'Il Mio Spazio',espaceSubtitle:'Accedi per seguire il tuo percorso',
    email:'Email',mdp:'Password',connexion:'Accedi',pasDeCompte:'Non hai un account?',
    demanderAcces:'📋 Richiedi accesso',deconnexion:'Disconnetti',
    reserverWA:'📱 Prenota su WhatsApp',commanderWA:'📱 Ordina su WhatsApp',
    precedente:'← Precedente',suivante:'Successivo →',
    lecon:'LEZIONE',hadithJour:'HADITH',
    quotidien:'📿 Quotidiano',salawat12k:'🌹 Salawat 12k',postOumra:'🕋 Post-Umrah 40g',
    progrPost:'PROGRESSO POST-UMRAH',accompli:'% completato',
    mabrouk:'🕋 Guida completata — Mabrouk!',lecons30:'🌟 30 lezioni completate!',
    envoyerWA:'📱 Invia su WhatsApp',retour:'← Indietro',
    bilanPrieres:'Le mie preghiere',toutesPrieres:'✅ Tutte complete — +500 Hasanat',
    resetSemaine:'↺ Reset settimana',groupePlus:'+100 in gruppo',
    nosPackages:'I Nostri Pacchetti',zamzamDattes:'Zamzam · Datteri · Profumi',
    quickAccess:'Accesso rapido',departIn:'PARTENZA TRA',days:'giorni',
    duaPerso:'Du\'a Personale',quiz:'Quiz',sadaqa:'Sadaqa',zakat:'Zakat',miras:'Miras',
    promo:'🔥 PROMO',standard:'Standard',vip:'⭐ VIP',premium:'Premium',
    placesLimites:'Posti limitati',reserWA:'📱 Prenota su WhatsApp',
    offreLimitee:'🔥 OFFERTA LIMITATA',oumraJuin:'Umrah Giugno 2026',datesJuin:'Dal 20 al 30 Giugno',
    zakatTitle:'⚖️ Calcolatore Zakat',zakatSubtitle:'Calcola la tua Zakat in base alla ricchezza',
    mirasTitle:'📜 Eredità Islamica (Miras)',mirasSubtitle:'Calcolatore automatico di successione',
  },
};
