const LANGS={
  fr:{flag:'🇫🇷',name:'Français',dir:'ltr',
    appName:'Kyswa Travel',guide:'Meilleur Guide',
    accueil:'Accueil',sira:'Sira',infos:'Infos',guide_nav:'Guide',baraka:'Baraka',dhikr:'Dhikr',espace:'Espace',
    notifTitle:'Activer les rappels',notifDesc:'Azan · Sira · Azkar · Salawat',notifBtn:'Activer',
    prochaineP:'Prochaine prière',restant:'restant',
    siraTitle:'Vie du Prophète ﷺ',siraSubtitle:'Leçon quotidienne · Hadith du jour',
    infosTitle:'Infos Pratiques',infosSubtitle:'Climat · Interdits Ihram · Bagages · Santé',
    climat:'🌡️ Climat',interdits:'🚫 Interdits',bagages:'🎒 Bagages',sante:'💊 Santé',
    guideTitle:'Guide Complet Oumra',guideSubtitle:'Invocations étape par étape',
    barakaTitle:'Programme Baraka',hasanat:"VOS HASANAT AUJOURD'HUI",
    packagesTitle:'Nos Packages 2026',
    boutiqueTitle:'Boutique Kyswa',
    dhikrTitle:'Dhikr & Tasbih',
    espaceTitle:'Mon Espace',espaceSubtitle:'Connectez-vous pour suivre votre parcours',
    email:'Email',mdp:'Mot de passe',connexion:'Se connecter',pasDeCompte:'Pas encore de compte ?',
    demanderAcces:'📋 Demander un accès',deconnexion:'Déconnexion',
    reserverWA:'📱 Réserver via WhatsApp',commanderWA:'📱 Commander via WhatsApp',
    precedente:'← Précédente',suivante:'Suivante →',
    lecon:'LEÇON',hadithJour:'HADITH',
    quotidien:'📿 Quotidien',salawat12k:'🌹 Salawat 12k',postOumra:'🕋 Post-Oumra 40j',
    progrPost:'PROGRESSION POST-OUMRA',accompli:'% accompli',
    mabrouk:'🕋 Guide terminé — Mabrouk !',lecons30:'🌟 30 leçons terminées !',
    envoyerWA:'📱 Envoyer via WhatsApp',retour:'← Retour',
    bilanPrieres:'Bilan de mes prières',toutesPrieres:'✅ Toutes accomplies — +500 Hasanat',
    resetSemaine:'↺ Reset semaine',groupePlus:'+100 en groupe',
    nosPackages:'Nos Packages',zamzamDattes:'Zamzam · Dattes · Parfums',
  },
  en:{flag:'🇬🇧',name:'English',dir:'ltr',
    appName:'Kyswa Travel',guide:'Best Guide',
    accueil:'Home',sira:'Sira',infos:'Info',guide_nav:'Guide',baraka:'Baraka',dhikr:'Dhikr',espace:'Space',
    notifTitle:'Enable daily reminders',notifDesc:'Adhan · Sira · Dhikr · Salawat',notifBtn:'Enable',
    prochaineP:'Next prayer',restant:'remaining',
    siraTitle:'Life of the Prophet ﷺ',siraSubtitle:'Daily lesson · Hadith of the day',
    infosTitle:'Practical Info',infosSubtitle:'Climate · Ihram Rules · Luggage · Health',
    climat:'🌡️ Climate',interdits:'🚫 Prohibitions',bagages:'🎒 Luggage',sante:'💊 Health',
    guideTitle:'Complete Umrah Guide',guideSubtitle:'Step by step invocations',
    barakaTitle:'Baraka Program',hasanat:'YOUR HASANAT TODAY',
    packagesTitle:'Our 2026 Packages',
    boutiqueTitle:'Kyswa Shop',
    dhikrTitle:'Dhikr & Tasbih',
    espaceTitle:'My Space',espaceSubtitle:'Login to track your journey',
    email:'Email',mdp:'Password',connexion:'Login',pasDeCompte:'No account yet?',
    demanderAcces:'📋 Request access',deconnexion:'Logout',
    reserverWA:'📱 Book via WhatsApp',commanderWA:'📱 Order via WhatsApp',
    precedente:'← Previous',suivante:'Next →',
    lecon:'LESSON',hadithJour:'HADITH',
    quotidien:'📿 Daily',salawat12k:'🌹 Salawat 12k',postOumra:'🕋 Post-Umrah 40d',
    progrPost:'POST-UMRAH PROGRESS',accompli:'% complete',
    mabrouk:'🕋 Guide complete — Mabrouk!',lecons30:'🌟 30 lessons done!',
    envoyerWA:'📱 Send via WhatsApp',retour:'← Back',
    bilanPrieres:'My prayer report',toutesPrieres:'✅ All done — +500 Hasanat',
    resetSemaine:'↺ Reset week',groupePlus:'+100 in group',
    nosPackages:'Our Packages',zamzamDattes:'Zamzam · Dates · Perfumes',
  },
  ar:{flag:'🇸🇦',name:'العربية',dir:'rtl',
    appName:'كيسوا ترافيل',guide:'أفضل مرشد',
    accueil:'الرئيسية',sira:'السيرة',infos:'معلومات',guide_nav:'الدليل',baraka:'البركة',dhikr:'الذكر',espace:'حسابي',
    notifTitle:'تفعيل التنبيهات اليومية',notifDesc:'الأذان · السيرة · الأذكار · الصلاة على النبي',notifBtn:'تفعيل',
    prochaineP:'الصلاة القادمة',restant:'متبقي',
    siraTitle:'حياة النبي ﷺ',siraSubtitle:'درس يومي · حديث اليوم',
    infosTitle:'معلومات عملية',infosSubtitle:'المناخ · محظورات الإحرام · الأمتعة · الصحة',
    climat:'🌡️ المناخ',interdits:'🚫 المحظورات',bagages:'🎒 الأمتعة',sante:'💊 الصحة',
    guideTitle:'دليل العمرة الكامل',guideSubtitle:'الأدعية خطوة بخطوة',
    barakaTitle:'برنامج البركة',hasanat:'حسناتك اليوم',
    packagesTitle:'باقاتنا 2026',
    boutiqueTitle:'متجر كيسوا',
    dhikrTitle:'الذكر والتسبيح',
    espaceTitle:'حسابي',espaceSubtitle:'سجّل دخولك لمتابعة رحلتك',
    email:'البريد الإلكتروني',mdp:'كلمة المرور',connexion:'تسجيل الدخول',pasDeCompte:'ليس لديك حساب؟',
    demanderAcces:'📋 طلب وصول',deconnexion:'تسجيل الخروج',
    reserverWA:'📱 احجز عبر واتساب',commanderWA:'📱 اطلب عبر واتساب',
    precedente:'→ السابق',suivante:'التالي ←',
    lecon:'الدرس',hadithJour:'الحديث',
    quotidien:'📿 يومي',salawat12k:'🌹 الصلاة 12k',postOumra:'🕋 ما بعد العمرة 40 يوم',
    progrPost:'تقدم ما après العمرة',accompli:'٪ مكتمل',
    mabrouk:'🕋 اكتمل الدليل — مبروك!',lecons30:'🌟 اكتملت 30 درساً!',
    envoyerWA:'📱 أرسل عبر واتساب',retour:'رجوع →',
    bilanPrieres:'تقرير صلواتي',toutesPrieres:'✅ كل الصلوات — +500 حسنة',
    resetSemaine:'↺ إعادة الأسبوع',groupePlus:'+100 جماعة',
    nosPackages:'باقاتنا',zamzamDattes:'زمزم · تمر · عطور',
  },
  wo:{flag:'🌍',name:'Wolof',dir:'ltr',
    appName:'Kyswa Travel',guide:'Guide bu baax',
    accueil:'Kër',sira:'Sira',infos:'Xibaar',guide_nav:'Guide',baraka:'Baraka',dhikr:'Dhikr',espace:'Sama Nokk',
    notifTitle:'Seeteel yëgëleem yi',notifDesc:'Azan · Sira · Dhikr · Salawat',notifBtn:'Seet',
    prochaineP:'Jikko bi dëkk',restant:'def',
    siraTitle:'Yëgëleem Nabi ﷺ',siraSubtitle:'Ders bu bépp bés · Hadith',
    infosTitle:'Xibaar yu malal',infosSubtitle:'Xëlam · Ihram · Valiz · Wérëf',
    climat:'🌡️ Xëlam',interdits:'🚫 Yëgël doo def',bagages:'🎒 Valiz',sante:'💊 Wérëf',
    guideTitle:'Guide Oumra bu xëtu',guideSubtitle:'Duwaaw ci kéb kéb',
    barakaTitle:'Programme Baraka',hasanat:'SA HASANAT TËEY',
    packagesTitle:'Ak Packages yi 2026',
    boutiqueTitle:'Boutique Kyswa',
    dhikrTitle:'Dhikr & Tasbih',
    espaceTitle:'Sama Nokk',espaceSubtitle:'Dugël ngir xool sa yëgëleem',
    email:'Email',mdp:'Mot de passe',connexion:'Dugël',pasDeCompte:'Amul konte?',
    demanderAcces:'📋 Dëmmeel accès',deconnexion:'Fey',
    reserverWA:'📱 Jël ci WhatsApp',commanderWA:'📱 Yëgël ci WhatsApp',
    precedente:'← Yangi',suivante:'Ci kanam →',
    lecon:'DERS',hadithJour:'HADITH',
    quotidien:'📿 Bépp bés',salawat12k:'🌹 Salawat 12k',postOumra:'🕋 Gannaaw Oumra 40j',
    progrPost:'PROGRESS GANNAAW OUMRA',accompli:'% jeex',
    mabrouk:'🕋 Guide jeex — Mabrouk!',lecons30:'🌟 Ders 30 jeex!',
    envoyerWA:'📱 Yónnee ci WhatsApp',retour:'← Dellu',
    bilanPrieres:'Sama jikko yi',toutesPrieres:'✅ Jikko yépp — +500 Hasanat',
    resetSemaine:'↺ Reboot ayu-bés',groupePlus:'+100 ci simili',
    nosPackages:'Packages yi',zamzamDattes:'Zamzam · Tamer · Pafin',
  },
  es:{flag:'🇪🇸',name:'Español',dir:'ltr',
    appName:'Kyswa Travel',guide:'Mejor Guía',
    accueil:'Inicio',sira:'Sira',infos:'Info',guide_nav:'Guía',baraka:'Baraka',dhikr:'Dhikr',espace:'Mi Espacio',
    notifTitle:'Activar recordatorios',notifDesc:'Adhan · Sira · Dhikr · Salawat',notifBtn:'Activar',
    prochaineP:'Próxima oración',restant:'restante',
    siraTitle:'Vida del Profeta ﷺ',siraSubtitle:'Lección diaria · Hadith del día',
    infosTitle:'Información Práctica',infosSubtitle:'Clima · Prohibiciones Ihram · Equipaje · Salud',
    climat:'🌡️ Clima',interdits:'🚫 Prohibiciones',bagages:'🎒 Equipaje',sante:'💊 Salud',
    guideTitle:'Guía Completa de Umrah',guideSubtitle:'Invocaciones paso a paso',
    barakaTitle:'Programa Baraka',hasanat:'TUS HASANAT HOY',
    packagesTitle:'Nuestros Paquetes 2026',
    boutiqueTitle:'Tienda Kyswa',
    dhikrTitle:'Dhikr & Tasbih',
    espaceTitle:'Mi Espacio',espaceSubtitle:'Inicia sesión para seguir tu voyage',
    email:'Correo electrónico',mdp:'Contraseña',connexion:'Iniciar sesión',pasDeCompte:'¿Sin cuenta aún?',
    demanderAcces:'📋 Solicitar acceso',deconnexion:'Cerrar sesión',
    reserverWA:'📱 Reservar por WhatsApp',commanderWA:'📱 Pedir por WhatsApp',
    precedente:'← Anterior',suivante:'Siguiente →',
    lecon:'LECCIÓN',hadithJour:'HADITH',
    quotidien:'📿 Diario',salawat12k:'🌹 Salawat 12k',postOumra:'🕋 Post-Umrah 40d',
    progrPost:'PROGRESO POST-UMRAH',accompli:'% completado',
    mabrouk:'🕋 Guía completa — ¡Mabrouk!',lecons30:'🌟 ¡30 lecciones completadas!',
    envoyerWA:'📱 Enviar por WhatsApp',retour:'← Volver',
    bilanPrieres:'Mis oraciones de hoy',toutesPrieres:'✅ Todas completas — +500 Hasanat',
    resetSemaine:'↺ Reiniciar semana',groupePlus:'+100 en grupo',
    nosPackages:'Nuestros Paquetes',zamzamDattes:'Zamzam · Dátiles · Perfumes',
  },
  it:{flag:'🇮🇹',name:'Italiano',dir:'ltr',
    appName:'Kyswa Travel',guide:'Miglior Guida',
    accueil:'Home',sira:'Sira',infos:'Info',guide_nav:'Guida',baraka:'Baraka',dhikr:'Dhikr',espace:'Il Mio Spazio',
    notifTitle:'Attiva i promemoria',notifDesc:'Adhan · Sira · Dhikr · Salawat',notifBtn:'Attiva',
    prochaineP:'Prossima preghiera',restant:'rimanente',
    siraTitle:'Vita del Profeta ﷺ',siraSubtitle:'Lezione quotidiana · Hadith del giorno',
    infosTitle:'Informazioni Pratiche',infosSubtitle:'Clima · Divieti Ihram · Bagagli · Salute',
    climat:'🌡️ Clima',interdits:'🚫 Divieti',bagages:'🎒 Bagagli',sante:'💊 Salute',
    guideTitle:'Guida Completa Umrah',guideSubtitle:'Invocations passe après passe',
    barakaTitle:'Programma Baraka',hasanat:'I TUOI HASANAT OGGI',
    packagesTitle:'I Nostri Pacchetti 2026',
    boutiqueTitle:'Negozio Kyswa',
    dhikrTitle:'Dhikr & Tasbih',
    espaceTitle:'Il Mio Spazio',espaceSubtitle:'Accedi per seguire il tuo percorso',
    email:'Email',mdp:'Password',connexion:'Accedi',pasDeCompte:'Non hai un account?',
    demanderAcces:'📋 Richiedi accesso',deconnexion:'Disconnetti',
    reserverWA:'📱 Prenota su WhatsApp',commanderWA:'📱 Ordina su WhatsApp',
    precedente:'← Precedente',suivante:'Successivo →',
    lecon:'LEZIONE',hadithJour:'HADITH',
    quotidien:'📿 Quotidiano',salawat12k:'🌹 Salawat 12k',postOumra:'🕋 Post-Umrah 40g',
    progrPost:'PROGRESSO POST-UMRAH',accompli:'% completato',
    mabrouk:'🕋 Guida completata — Mabrouk!',lecons30:'🌟 30 lezioni completate!',
    envoyerWA:'📱 Invia su WhatsApp',retour:'← Indietro',
    bilanPrieres:'Le mie preghiere',toutesPrieres:'✅ Tutte complete — +500 Hasanat',
    resetSemaine:'↺ Reset settimana',groupePlus:'+100 in gruppo',
    nosPackages:'I Nostri Pacchetti',zamzamDattes:'Zamzam · Datteri · Profumi',
  },
};
